dist: xenial
language: node_js
node_js:
  - "10.15.3"
before_script:
  - sudo service mongod stop
  - sudo apt-get purge mongodb-org*
  - sudo rm -rf /var/log/mongodb
  - sudo rm -rf /var/lib/mongodb
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | sudo apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=4.0.23
  - sudo service mongod start
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongo --version