sudo: false
language: node_js
node_js:
  - "6.9.4"
  - "7.4.0"
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongo --version