sudo: false
language: node_js
node_js:
  - "8.10.0"
  - "9.9.0"
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.4-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongo --version