language: node_js
node_js:
  - "6.9.4"
  - "7.4.0"
before_install:
  - "sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10"
  - "echo 'deb http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.2 multiverse' | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list"
  - "sudo apt-get update"
  - "sudo apt-get install mongodb-org-server"
  - "sudo apt-get install mongodb-org-shell"
before_script:
  - "until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done"
  - mongo --version